plugins {
    id 'com.android.application'
}

android {
    namespace 'com.amtandroid.quotebuilder'
    compileSdk 36

    defaultConfig {
        applicationId "com.amtandroid.quotebuilder"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.activity:activity-ktx:1.9.3'
    implementation 'androidx.core:core-ktx:1.15.0'
}
